name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "<TITLE>"
type: "Bug"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please provide clear steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Drag and drop screenshots here, or paste image URLs using ![description](image-url)"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: platform
    attributes:
      label: "Platform"
      description: What platform(s) do you see the problem on?
      multiple: true
      options:
        - Android
        - Android TV
        - iOS
        - Linux
        - Windows
        - macOS
        - Web
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of Fladder are you using?
      placeholder: e.g. v0.7.0 (267)
  - type: input
    id: server
    attributes:
      label: Jellyfin server
      description: What is your Jellyfin setup
      placeholder: e.g. 10.11.2 on docker,windows,macos
    validations:
      required: true
